parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true

extends:
  - airbnb
  - airbnb/hooks
  - prettier
  - prettier/react

plugins:
  - import
  - react
  - react-hooks
  - prettier

rules:
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  no-param-reassign: off
  prettier/prettier: error
  camelcase: warn
  react/jsx-props-no-spreading: off
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .js
        - .jsx
  consistent-return: off
  react/forbid-prop-types: off
  import/no-unresolved: off
