parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  ecmaFeatures:
    jsx: true

env:
  browser: true
  es6: true

extends:
  - eslint:recommended
  - airbnb
  - airbnb/hooks
  - plugin:prettier/recommended

rules:
  no-param-reassign: off
  camelcase: off
  consistent-return: off

  react/jsx-props-no-spreading: off
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .js
        - .jsx
  react/forbid-prop-types: off
  react/jsx-one-expression-per-line: off
  react/jsx-wrap-multilines: off

  import/no-unresolved: off
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  import/no-cycle: off
  import/prefer-default-export: off
